# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 update:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Get new code
    - run: git pull origin main
    - name: Stop DaneeCloud
    - run: pm2 stop daneecloud
    - name: Install NPM Packages
    - run: npm i
    - name: Start DaneeCloud
    - run: pm2 start daneecloud
